### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by basmoura** [basmoura/c3p0#1]
- [ ] Authenticate with AWS S3
- [ ] Create method to create a bucket
- [ ] Create method to delete a bucket
- [ ] Create method to empty a bucket
- [ ] Create method to retrieve bucket files
- [ ] Create method to upload file to a bucket
- [ ] Create method to remove a file from a bucket
